trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Images to build
strategy:
  matrix:
    centos:
      BASE_IMAGE:     centos
      BASE_IMAGE_TAG: 7
      INSTALL_CONFIG: centos
    ubuntu:
      BASE_IMAGE:     ubuntu
      BASE_IMAGE_TAG: 16.04
      INSTALL_CONFIG: ubuntu

# Steps to build images
steps:
- script: |
    printf "##vso[task.setvariable variable=DATE_TAG;]%s\n" $(date "+%g.%m")
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: liambindle/build-matrix-images-base
    tags: $(DATE_TAG)-$(BASE_IMAGE)
    arguments: |
      --build-arg BASE_IMAGE=$(BASE_IMAGE)
      --build-arg BASE_IMAGE_TAG=$(BASE_IMAGE_TAG) 
      --build-arg INSTALL_CONFIG=$(INSTALL_CONFIG) 
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub
    repository: liambindle/build-matrix-images-base
    command: push
    tags: |
      $(DATE_TAG)-$(BASE_IMAGE)