trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  ZLIB_COMMON:        1.2.11
  HDF5_COMMON:        1.10.5
  NETCDF_C_NEW:       4.7.1
  NETCDF_FORTRAN_NEW: 4.4.5
  NETCDF_C_OLD:       4.1.3

# Images to build
strategy:
  matrix:
    centos:
      BASE_IMAGE:         centos
      BASE_IMAGE_VERSION: 7
      INSTALL_CONFIG:     centos
    ubuntu:
      BASE_IMAGE:         ubuntu
      BASE_IMAGE_VERSION: 16.04
      INSTALL_CONFIG:     ubuntu

# Steps to build images
steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: liambindle/build-matrix-images-base
    tags: $(Date:yyyy.MM.dd)$(GCC_VERSION)-$(BASE_IMAGE)
    arguments: |
      --build-arg BASE_IMAGE=$(BASE_IMAGE)
      --build-arg BASE_IMAGE_VERSION=$(BASE_IMAGE_VERSION) 
      --build-arg INSTALL_CONFIG=$(INSTALL_CONFIG) 
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub
    repository: liambindle/build-matrix-images-base
    command: push
    tags: |
      $(Date:yyyy.MM.dd)$(GCC_VERSION)-$(BASE_IMAGE)